/* eslint global-require: 0 */

const mentors = [
  {
    name: 'Rohan Mathur',
    image: require('assets/Mentors/mathur.png'),
    project: 'LineageOS',
    description:
      'LineageOS is an open-source operating system for smartphones, ' +
      'tablets and set-top boxes, based on the Android operating system. It supports ' +
      'over 100 devices, and contains several enhancements not found in stock Android, ' +
      'such as customized UI elements, privacy enhancements, and more.',
    github: 'mathur',
    room: 'ECEB 3013',
  },
  {
    name: 'Michael Tamillow',
    project: 'AgentPy',
    image: require('assets/Mentors/mtamillow.jpeg'),
    description: '',
    github: 'mtamillow',
    room: 'Siebel 1103',
  },
  {
    name: 'Zac Codiamat',
    image: '',
    project: 'AirOnTime',
    description: 'Flight on-time reliability search engine',
    github: '',
    room: 'Siebel 1103',
  },
  {
    name: 'Amber Sahdev',
    image: '',
    project: 'AirOnTime',
    description: 'Flight on-time reliability search engine',
    github: '',
    room: 'Siebel 1103',
  },
  {
    name: 'Shelby Switzer',
    image: require('assets/Mentors/switzersc.jpeg'),
    project: 'Open Referral Transformer',
    description:
      'The Open Referral Transformer is a tool to help organizations convert their health and human services data into an Open Referral Human Services Data Spec compliant datapackage. We will work with data provided by Illinois Legal Aid Online (ILAO) as our foundation.',
    github: 'switzersc',
    room: 'Siebel 1131',
  },
  {
    name: 'Jonathan Helmus',
    image: require('assets/Mentors/jjhelmus.jpeg'),
    project: 'conda',
    description:
      'Conda is an open source package management system and environment management system that runs on Windows, macOS and Linux. Conda quickly installs, runs and updates packages and their dependencies. Conda easily creates, saves, loads and switches between environments on your local computer. It was created for Python programs, but it can package and distribute software for any language.',
    github: 'jjhelmus',
    room: 'Siebel 1302',
  },
  {
    name: 'Tom Fischer',
    image: '',
    project: 'Confbase',
    description: 'Tool for managing configuration files',
    github: '',
    room: 'ECEB 3015',
  },
  {
    name: 'Ish Shah',
    image: '',
    project: 'Confbase',
    description: 'Tool for managing configuration files',
    github: '',
    room: 'ECEB 3015',
  },
  {
    name: 'Drake Eidukas',
    image: '',
    project: 'Confbase',
    description: 'Tool for managing configuration files',
    github: '',
    room: 'ECEB 3015',
  },
  {
    name: 'Paul Ganssle',
    image: require('assets/Mentors/pganssle.jpeg'),
    project: 'dateutil',
    description:
      'A widely used library providing useful datetime functions and classes such as time zones, recurrence rules and a parser.',
    github: 'pganssle',
    room: 'Siebel 1302',
  },
  {
    name: 'Evan Hazlett',
    image: require('assets/Mentors/ehazlett.jpeg'),
    project: 'Docker',
    description: '',
    github: 'ehazlett',
    room: 'ECEB 2015',
  },
  {
    name: 'Michael Crosby',
    image: require('assets/Mentors/crosbymichael.jpeg'),
    project: 'containerd',
    description:
      'containerd industry-standard container runtime with an emphasis on simplicity, robustness and portability.  It has been written in Go and provides an API built on gRPC.  It handles content, overlay filesystems, distribution of images, and the execution and lifecycle of Linux and Windows containers for platforms like Docker and Kubernetes.',
    github: 'crosbymichael',
    room: 'ECEB 3015',
  },
  {
    name: 'Phil Mesnier',
    image: require('assets/Mentors/pmesnier.png'),
    project: 'EOS',
    description:
      'Blockchain event notifier service. Help build a new plugin module and some representative front-end usage examples.',
    github: 'pmesnier',
    room: 'ECEB 3013',
  },
  {
    name: 'Douglas Wilson',
    image: require('assets/Mentors/dougwilson.jpeg'),
    project: 'Express',
    description: 'Express.js is a HTTP server framework for Node.js',
    github: 'dougwilson',
    room: 'Siebel 1302',
  },
  {
    name: 'David Dias',
    image: require('assets/Mentors/thedaviddias.jpeg'),
    project: 'HTMLHint',
    description:
      'HTMLHint is a static code analysis tool that analyses your HTML to find possible issues.',
    github: 'thedaviddias',
    room: 'Siebel 1131',
  },
  {
    name: 'Tony Crisci',
    image: require('assets/Mentors/acrisci.png'),
    project: 'Git',
    description: '',
    github: 'acrisci',
    room: 'ECEB 3013',
  },
  {
    name: 'Brett Koonce',
    image: require('assets/Mentors/asparagui.png'),
    project: 'Homebrew',
    description: 'A unix package manager for mac/linux.',
    github: 'asparagui',
    room: 'ECEB 3017',
  },
  {
    name: 'Lewis McGibbney',
    image: '',
    project: 'HTrace',
    description: '',
    github: '',
    room: 'ECEB 2015',
  },
  {
    name: 'Zac Delventhal',
    image: '',
    project: 'Hyperledger Sawtooth (and Grid)',
    description:
      'An enterprise solution for building, deploying, and running custom blockchains. It provides an extremely modular and flexible platform for sharing cryptographically protected data between untrusted parties.',
    github: '',
    room: 'ECEB 3015',
  },
  {
    name: 'Matt Mariutto',
    image: '',
    project: 'HyperLedger',
    description: 'Open Source Blockchain Technologies',
    github: '',
    room: 'ECEB 3015',
  },
  {
    name: 'Rob Miroballi',
    image: '',
    project: 'HyperLedger',
    description: 'Open Source Blockchain Technologies',
    github: '',
    room: 'ECEB 3015',
  },
  {
    name: 'Katharine Hyatt',
    image: require('assets/Mentors/kshyatt.jpeg'),
    project: 'Julia',
    description: '',
    github: 'kshyatt',
    room: 'Siebel 1111',
  },
  {
    name: 'Shaoyu',
    image: '',
    project: 'Lifefoundry',
    description: '',
    github: '',
    room: '',
  },
  {
    name: 'Cody Sherman',
    image: '',
    project: 'Vue-BabylonJS',
    description: 'A ready-to-go 3d environment for Vue.js using Babylon.js',
    github: '',
    room: 'Siebel 1131',
  },
  {
    name: 'Richard Kim',
    image: '',
    project: 'NodeSchool',
    description: '',
    github: '',
    room: 'Siebel 1131',
  },
  {
    name: 'Johnmark Beaty',
    image: '',
    project: 'NodeSchool',
    description: '',
    github: '',
    room: 'Siebel 1131',
  },
  {
    name: 'Sam Moore',
    image: '',
    project: 'Vue-BabylonJS',
    description: 'A ready-to-go 3d environment for Vue.js using Babylon.js',
    github: '',
    room: 'Siebel 1131',
  },
  {
    name: 'Brandon Frisch',
    image: '',
    project: 'NodeSchool',
    description: '',
    github: '',
    room: 'Siebel 1131',
  },
  {
    name: 'Brian Jesse',
    image: require('assets/Mentors/BrainBacon.jpeg'),
    project: 'Vue-BabylonJS',
    description: '3D Graphics plugin for Vue.js in the browser',
    github: 'BrainBacon',
    room: 'Siebel 1131',
  },
  {
    name: 'Benjamin Coe',
    image: require('assets/Mentors/bcoe.png'),
    project: 'Npm',
    description:
      'npm is the open source package manager that help JavaScript developers easily share packaged modules of code. Behind is the the npm Registry, a public collection of packages of open-source code for Node.js, front-end web apps, mobile apps, robots, and countless other. npm is also the command line interface client that allows developers to install and publish those packages.',
    github: 'bcoe',
    room: 'Siebel 1304',
  },
  {
    name: 'Frederic Harper',
    image: '',
    project: 'Npm',
    description:
      'npm is the open source package manager that help JavaScript developers easily share packaged modules of code. Behind is the the npm Registry, a public collection of packages of open-source code for Node.js, front-end web apps, mobile apps, robots, and countless other. npm is also the command line interface client that allows developers to install and publish those packages.',
    github: '',
    room: 'Siebel 1304',
  },
  {
    name: 'Tyler Leonhardt',
    image: '',
    project: 'PowerShell',
    description:
      "PowerShell Core is an object-oriented command-line shell and scripting language built on .NET. PowerShell helps system administrators and power-users rapidly automate tasks that manage operating systems (Linux, macOS, and Windows) and processes.\nPowerShell is designed to improve the command-line and scripting environment by putting discoverability, consistency, and objects first.\n\nOh, and it's open source and free.",
    github: '',
    room: 'ECEB 3002',
  },
  {
    name: 'Andrew Schwartzmeyer',
    image: require('assets/Mentors/andschwa.jpeg'),
    project: 'Open Enclave SDK',
    description:
      'Open Enclave is an SDK for building enclave applications in C and C++. An enclave application partitions itself into two components (1) An untrusted component (called the host) and (2) A trusted component (called the enclave). An enclave is a secure container whose memory is protected from entities outside the enclave. These protections allow enclaves to perform secure computations with assurances that secrets will not be compromised.',
    github: 'andschwa',
    room: 'ECEB 3002',
  },
  {
    name: 'Akash Gupta',
    image: '',
    project: 'Open Enclave SDK',
    description:
      'OpenEnclave is an C/C++ SDK for writing enclave applications. Enclave applications are segmented into a trusted "enclave" portion and an untrusted "host" portion. The memory in the enclave portion is protected from the outside world through the use of processor specific isolation technology like Intel SGX or ARM TrustZone. This ensures that contents in the enclave are secure even if the host is compromised.',
    github: '',
    room: 'ECEB 3002',
  },
  {
    name: 'Robert Holt',
    image: require('assets/Mentors/rjmholt.jpeg'),
    project: 'Powershell',
    description: '',
    github: 'rjmholt',
    room: 'ECEB 3002',
  },
  {
    name: 'Matthew Turk',
    image: require('assets/Mentors/MatthewTurk.jpeg'),
    project: 'yt',
    description:
      'Analyze and visualize data from lots of different sources -- astronomy, brain scans, materials science, and so on!',
    github: 'MatthewTurk',
    room: 'Siebel 1103',
  },
  {
    name: 'Timothy Bretl',
    image: require('assets/Mentors/tbretl.jpeg'),
    project: 'PrairieLearn',
    description: '',
    github: 'tbretl',
    room: 'Siebel 1109',
  },
  {
    name: 'Matthew West',
    image: require('assets/Mentors/mwest1066.jpeg'),
    project: 'Illinois Open Source',
    description:
      'A collection of open-source projects that are used throughout UIUC. PrairieLearn (https://github.com/PrairieLearn/PrairieLearn) is used to offer customizable and powerful questions on homework and exams. The Queue (https://github.com/illinois/queue) is used to power open office hours, academic advising, lectures, and more. Come help shape the future of education at Illinois!',
    github: 'mwest1066',
    room: 'Siebel 1109',
  },
  {
    name: 'Nathan Walters',
    image: require('assets/Mentors/nwalters512.jpeg'),
    project: 'Illinois Open Source',
    description:
      'A collection of open-source projects that are used throughout UIUC. PrairieLearn (https://github.com/PrairieLearn/PrairieLearn) is used to offer customizable and powerful questions on homework and exams. The Queue (https://github.com/illinois/queue) is used to power open office hours, academic advising, lectures, and more. Come help shape the future of education at Illinois!',
    github: 'nwalters512',
    room: 'Siebel 1109',
  },
  {
    name: 'Craig Zilles',
    image: require('assets/Mentors/zillesc.png'),
    project: 'PrairieLearn',
    description: '',
    github: 'zillesc',
    room: 'Siebel 1109',
  },
  {
    name: 'Alex Chrichton',
    image: require('assets/Mentors/alexcrichton.jpeg'),
    project: 'Rust',
    description:
      "Rust is a new blazingly fast and safe programming language and WebAssembly is a new blazingly fast and safe VM for the web, a perfect match! The Rust and WebAssembly Working Group is working to make Rust and WebAssembly a dream come true, and we're always looking for more to help out!",
    github: 'alexcrichton',
    room: 'ECEB 3002',
  },
  {
    name: 'Trent Spice',
    image: require('assets/Mentors/trentspi.jpeg'),
    project: 'Rust Cookbook',
    description:
      'This Rust Cookbook is a collection of simple examples that demonstrate good practices to accomplish common programming tasks, using the crates of the Rust ecosystem.',
    github: 'trentspi',
    room: 'ECEB 3002',
  },
  {
    name: 'Brock Mendel',
    image: require('assets/Mentors/ChadFulton.jpeg'),
    project: 'statsmodels',
    description: '',
    github: 'ChadFulton',
    room: 'Siebel 1111',
  },
  {
    name: 'Pablo Aguiar',
    image: '',
    project: 'Mort and OpenCV',
    description:
      'Project consists of adding face recognition and feature detection support to Mort with OpenCV. Mort is a MIT-licensed storage and image processing server written in Go. Check its features: https://github.com/aldor007/mort#features. OpenCV (Open Source Computer Vision Library) is an open-source BSD-licensed library that includes several hundreds of computer vision algorithms. Check https://www.opencv.org and https://gocv.io',
    github: '',
    room: 'ECEB 2017',
  },
  {
    name: 'Vladyslav Shcherbyna',
    image: require('assets/Mentors/valdislav.jpeg'),
    project: 'Translations',
    description:
      'Development environment for magento2 development aimed to make close to production environment. Current DevBox aims to support multi-service deployment in one click. It is optimized for development scenarios using local environment.',
    github: 'valdislav',
    room: 'ECEB 3002',
  },
  {
    name: 'Divya Sasidharan',
    image: require('assets/Mentors/shortdiv.jpeg'),
    project: 'Vue',
    description: '',
    github: 'shortdiv',
    room: 'Siebel 1103',
  },
  {
    name: 'Pranay Prakash',
    image: require('assets/Mentors/pranaygp.jpeg'),
    project: 'CSS Peek',
    description: 'A VS Plugin that makes working with CSS a breeze',
    github: 'pranaygp',
    room: 'Siebel 1104',
  },
  {
    name: 'Andrew Faust',
    image: '',
    project: 'CSS Peek',
    description:
      'Extends HTML and ejs code editing with Go To Definition and Go To Symbol in Workspace support for css/scss/less (classes and IDs) found in strings within the source code. Supports all the normal capabilities of symbol definition tracking, but does it for css selectors (classes, IDs and HTML tags). ',
    github: '',
    room: 'Siebel 1104',
  },
  {
    name: 'Jason Coombs',
    image: require('assets/Mentors/jaraco.jpeg'),
    project: 'YouGov, CherryPy',
    description:
      'importlib_metadata is the draft project slated to become importlib.metadata in Python 3.8',
    github: 'jaraco',
    room: 'Siebel 1302',
  },
  {
    name: 'Tejas Kumar',
    image: '',
    project: 'ZEIT',
    description: '',
    github: '',
    room: 'Siebel 1103',
  },
  {
    name: 'Juan Campa',
    image: require('assets/Mentors/juancampa.jpeg'),
    project: 'Project ZEIT',
    description: '',
    github: 'juancampa',
    room: 'Siebel 1103',
  },
  {
    name: 'Christos Bacharakis',
    image: require('assets/Mentors/bacharakis.png'),
    project: 'Mozilla',
    description: '',
    github: 'bacharakis',
    room: 'ECEB 3013',
  },
];

export default mentors;
