export const range = [
  { text: '1', value: 1 },
  { text: '2', value: 2 },
  { text: '3', value: 3 },
  { text: '4', value: 4 },
  { text: '5', value: 5 },
];

export const yn = [{ text: 'Yes', value: true }, { text: 'No', value: false }];

export const shirtSizes = [
  { text: 'Small', value: 'S' },
  { text: 'Medium', value: 'M' },
  { text: 'Large', value: 'L' },
  { text: 'Extra-Large', value: 'XL' },
];

export const transportation = [
  { text: 'Will require travel assistance', value: 'BUS' },
  { text: 'Will not require travel assistance', value: 'NONE' },
];

export const diet = [
  { text: 'Vegan', value: 'VEGAN' },
  { text: 'Vegetarian', value: 'VEGETARIAN' },
  { text: 'Gluten Free', value: 'NOGLUTEN' },
  { text: 'Nut Allergy', value: 'NOPEANUT' },
];

export const genderOptions = [
  { text: 'Male', value: 'MALE' },
  { text: 'Female', value: 'FEMALE' },
  { text: 'Other', value: 'OTHER' },
  { text: 'Prefer not to answer', value: 'NOANSWER' },
];

export const careerInterests = [
  { text: 'Internship', value: 'INTERNSHIP' },
  { text: 'Full Time', value: 'FULLTIME' },
];

export const majors = [
  { text: 'Computer Science' },
  { text: 'Computer Engineering' },
  { text: 'Electrical Engineering' },
  { text: 'Engineering' },
  { text: 'Business' },
  { text: 'Sciences' },
  { text: 'Liberal Arts' },
  { text: 'Fine Arts' },
  { text: 'Other' },
];

export const schools = [
  { text: 'Anna University' },
  { text: 'Appalachian State University' },
  { text: 'Arizona State University' },
  { text: 'Babson College' },
  { text: 'Ball State University' },
  { text: 'Bard College' },
  { text: 'Barnard College' },
  { text: 'Baruch College' },
  { text: 'Bellevue College' },
  { text: 'Benha University' },
  { text: 'Binghamton University' },
  { text: 'Boise State University' },
  { text: 'Boston College' },
  { text: 'Boston University' },
  { text: 'Brown University' },
  { text: 'Bryn Mawr College' },
  { text: 'Bucknell University' },
  { text: 'California Institute of Technology' },
  { text: 'California Polytechnic State University' },
  { text: 'California State University-Long Beach' },
  { text: 'Carleton College' },
  { text: 'Carnegie Mellon University' },
  { text: 'Case Western Reserve University' },
  { text: 'Clark University' },
  { text: 'Colegio Americano de Torren' },
  { text: 'College of Dupage' },
  { text: 'College of William and Mary' },
  { text: 'Columbia University' },
  { text: 'Concordia University Wisconsin' },
  { text: 'Cornell University' },
  { text: 'DePaul University' },
  { text: 'DePauw University' },
  { text: 'Diablo Valley College' },
  { text: 'Drexel University' },
  { text: 'Duke University' },
  { text: 'Earlham College' },
  { text: 'Eastern Michigan University' },
  { text: 'Embry-Riddle Aeronautical University' },
  { text: 'Emory University' },
  { text: 'ETH Zurich' },
  { text: 'Florida Institute of Technology' },
  { text: 'Florida International University' },
  { text: 'Florida State University' },
  { text: 'Foothill College' },
  { text: 'George Mason University' },
  { text: 'George Washington University' },
  { text: 'Georgia Institute of Technology' },
  { text: 'Georgia State University' },
  { text: 'Grinnell College' },
  { text: 'Harper College' },
  { text: 'Harvard University' },
  { text: 'Howard University' },
  { text: 'Illinois Institute of Technology' },
  { text: 'Illinois State University' },
  { text: 'Illinois Wesleyan University' },
  { text: 'Indiana University - Bloomington' },
  { text: 'Indiana University - Purdue University Indianapolis' },
  { text: 'Iowa State University' },
  { text: 'Kansas State University' },
  { text: 'Kent State University' },
  { text: 'Knox College' },
  { text: 'Lehigh University' },
  { text: 'Lewis University' },
  { text: 'Liceo Tecnologico Scientifico Salesiani Don Bosco' },
  { text: 'Lindenwood University' },
  { text: 'Los Angeles Pierce College' },
  { text: 'Marist College' },
  { text: 'Marquette University' },
  { text: 'Massachusetts Institute of Technology' },
  { text: 'McGill University' },
  { text: 'McMaster University' },
  { text: 'Messiah College' },
  { text: 'Miami University' },
  { text: 'Michigan State University' },
  { text: 'Michigan Technological University' },
  { text: 'Middle Tennessee State University' },
  { text: 'Milwaukee School of Engineering' },
  { text: 'Mission College' },
  { text: 'Mississippi State University' },
  { text: 'Missouri State University' },
  { text: 'Monmouth College' },
  { text: 'New York University' },
  { text: 'New York University Shanghai' },
  { text: 'North Carolina State University' },
  { text: 'North Dakota State University' },
  { text: 'Northeastern Illinois University' },
  { text: 'Northeastern University' },
  { text: 'Northern Illinois University' },
  { text: 'Northwestern University' },
  { text: 'Notre Dame University' },
  { text: 'Oakton Community College' },
  { text: 'Ohio State University' },
  { text: 'Ohlone College' },
  { text: 'Oregon State University' },
  { text: 'Parkland College' },
  { text: 'Pennsylvania State University' },
  { text: "Prince George's Community College" },
  { text: 'Princeton University' },
  { text: 'Purdue University' },
  { text: "Queen's University" },
  { text: 'Rensselaer Polytechnic Institute' },
  { text: 'Rhode Island School of Design' },
  { text: 'Rice University' },
  { text: 'Rochester Institute of Technology' },
  { text: 'Rose-Hulman Institute of Technology' },
  { text: 'Rutgers University' },
  { text: 'Saginaw Valley State University' },
  { text: 'San Jose State University' },
  { text: 'Santa Clara University' },
  { text: 'Savannah College of Art and Design' },
  { text: 'School of Visual Arts' },
  { text: 'Southern Connecticut State University' },
  { text: 'Southern Illinois University - Carbondale' },
  { text: 'Southern Illinois University - Edwardsville' },
  { text: 'Southern Methodist University' },
  { text: 'St. Cloud State University' },
  { text: "St. John's University" },
  { text: 'St. Louis University' },
  { text: 'Stanford University' },
  { text: 'Stetson University' },
  { text: 'Stevens Institute of Technology' },
  { text: 'Stony Brook University' },
  { text: 'SUNY Albany' },
  { text: 'SUNY Stony Brook University' },
  { text: 'Tallahassee Community College' },
  { text: 'Tecnolgico de Monterrey (ITESM)' },
  { text: 'Temple University' },
  { text: 'Texas A&M University' },
  { text: 'The New School/Parsons' },
  { text: 'The University of North Carolina at Chapel Hill' },
  { text: 'The University of Texas at Dallas' },
  { text: 'Tufts University' },
  { text: 'Tulsa Community College' },
  { text: 'University College London (UCL)' },
  { text: 'University of Arizona' },
  { text: 'University of British Columbia' },
  { text: 'University of Buffalo' },
  { text: 'University of Calfornia - Los Angeles' },
  { text: 'University of California - Berkeley' },
  { text: 'University of California - Davis' },
  { text: 'University of California - Irvine' },
  { text: 'University of California - Merced' },
  { text: 'University of California - San Diego' },
  { text: 'University of California - Santa Barbara' },
  { text: 'University of California - Santa Cruz' },
  { text: 'University of Central Florida' },
  { text: 'University of Chicago' },
  { text: 'University of Cincinnati' },
  { text: 'University of Colorado - Boulder' },
  { text: 'University of Florida' },
  { text: 'University of Georgia' },
  { text: 'University of Houston' },
  { text: 'University of Illinois - Chicago' },
  { text: 'University of Illinois - SpringfieldType' },
  { text: 'University of Illinois Urbana - Champaign' },
  { text: 'University of Iowa' },
  { text: 'University of Kansas' },
  { text: 'University of Louisiana at Monroe' },
  { text: 'University of Louisville' },
  { text: 'University of Maryland' },
  { text: 'University of Maryland-Baltimore County' },
  { text: 'University of Massachusetts' },
  { text: 'University of Massachusetts Amherst' },
  { text: 'University of Michigan - Ann Arbor' },
  { text: 'University of Minnesota - Twin Cities' },
  { text: 'University of Missouri' },
  { text: 'University of Missouri - Kansas City' },
  { text: 'University of Nebraska - Lincoln' },
  { text: 'University of North Carolina at Chapel Hill' },
  { text: 'University of North Texas' },
  { text: 'University of Notre Dame' },
  { text: 'University of Oxford' },
  { text: 'University of Pennsylvania' },
  { text: 'University of Pittsburgh' },
  { text: 'University of Puerto Rico - Bayamon' },
  { text: 'University of Rochester' },
  { text: 'University of San Francisco' },
  { text: 'University of Southern California' },
  { text: 'University of Texas - Austin' },
  { text: 'University of Texas - Dallas' },
  { text: 'University of Texas Rio Grande Valley' },
  { text: 'University of Toledo' },
  { text: 'University of Toronto' },
  { text: 'University of Tulsa' },
  { text: 'University of Virginia' },
  { text: 'University of Washington' },
  { text: 'University of Waterloo' },
  { text: 'University of Windsor' },
  { text: 'University of Wisconsin - Madison' },
  { text: 'University of Wisconsin - Milwaukee' },
  { text: 'University of Wisconsin - Platteville' },
  { text: 'University Texas - Dallas' },
  { text: 'Vanderbilt University' },
  { text: 'Villanova University' },
  { text: 'Virginia Polytechnic Institute and State University (Virginia Tech)' },
  { text: 'Washington University in St. Louis' },
  { text: 'Westminster College' },
  { text: 'Wheaton College' },
  { text: 'Worcester Polytechnic Institute' },
  { text: 'Wright State University' },
  { text: 'Yale University' },
  { text: 'Other' },
];
